export default restaurantsData = [
    {
        id: "65797",
        name: "Leon's - Burgers & Wings (Leon Grill)",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/5/2/4c1e29e2-fecf-41b6-8b21-5a58338247fe_65797.jpg",
        locality: "Koramangala",
        area: "Koramangala",
        costForTwo: "₹300 for two",
        cuisines: ["American", "Snacks", "Turkish", "Portuguese", "Continental"],
        avgRating: 3.8,
        totalRatings: "52K+",
        deliveryTime: "25-30 mins",
        distance: "1.3 km",
        discount: "₹125 OFF - ABOVE ₹249"
    },
    {
        id: "711368",
        name: "Salad Days",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/cfa1123ebf17413dc7d0a80c7361fab3",
        locality: "BTM Layout",
        area: "HSR",
        costForTwo: "₹500 for two",
        cuisines: ["Salads"],
        avgRating: 4.5,
        totalRatings: "3.1K+",
        deliveryTime: "30-40 mins",
        distance: "3.8 km",
        discount: "40% OFF - UPTO ₹80",
        badges: ["Gourmet"]
    },
    {
        id: "375041",
        name: "Andhra Gunpowder",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/byilgyrcfz690ryoasww",
        locality: "6th Block",
        area: "Koramangala",
        costForTwo: "₹350 for two",
        cuisines: ["Andhra", "Biryani", "South Indian"],
        avgRating: 3.7,
        totalRatings: "5.1K+",
        deliveryTime: "20-30 mins",
        distance: "0.1 km",
        discount: "ITEMS AT ₹149"
    },
    {
        id: "769775",
        name: "Nahdi Mandi Restaurant",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/8e82f6e42f5e5bde0649f1f8f48209d8",
        locality: "BTM Layout",
        area: "BTM Layout",
        costForTwo: "₹450 for two",
        cuisines: ["Biryani", "Arabian", "North Indian"],
        avgRating: 4.5,
        totalRatings: "3.7K+",
        deliveryTime: "30-40 mins",
        distance: "2.0 km",
        discount: "20% OFF - UPTO ₹50"
    },
    {
        id: "793210",
        name: "Aattutheeram Kerala Restaurant",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/7dad18ba53a7f5fd4df728f9173ad706",
        locality: "Thippiah Layout",
        area: "Koramangala",
        costForTwo: "₹350 for two",
        cuisines: ["Kerala", "Biryani", "Chinese", "Snacks", "Seafood", "Desserts"],
        avgRating: 4.3,
        totalRatings: "454",
        deliveryTime: "25-35 mins",
        distance: "0.6 km",
        discount: "ITEMS AT ₹139"
    },
    {
        id: "56718",
        name: "Tapri By The Corner",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/qkqilt3jv17o7xs8ljfb",
        locality: "Koramangala",
        area: "Koramangala",
        costForTwo: "₹250 for two",
        cuisines: ["Chinese", "Snacks", "Indian"],
        avgRating: 4.0,
        totalRatings: "4.0K+",
        deliveryTime: "30-40 mins",
        distance: "0.4 km",
        discount: "60% OFF - UPTO ₹115",
        freeDelivery: true
    },
    {
        id: "201224",
        name: "Asha Tiffins",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/n15vckntsiboiod3gpco",
        locality: "HSR Layout",
        area: "HSR Layout",
        costForTwo: "₹200 for two",
        cuisines: ["South Indian", "Chinese", "Desserts", "Beverages", "North Indian"],
        avgRating: 4.5,
        totalRatings: "62K+",
        deliveryTime: "30-40 mins",
        distance: "4.0 km",
        discount: "50% OFF - UPTO ₹100",
        badges: ["Pure Veg"]
    },
    {
        id: "108097",
        name: "Ambur Star Briyani Since 1890",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/RX_THUMBNAIL/IMAGES/VENDOR/2024/6/12/bee2f2d5-6a39-477a-b669-c9df142ed5d0_108097.jpg",
        locality: "2nd Stage",
        area: "BTM Layout",
        costForTwo: "₹500 for two",
        cuisines: ["Biryani", "Chettinad", "Andhra", "Beverages", "Seafood"],
        avgRating: 4.5,
        totalRatings: "19K+",
        deliveryTime: "30-40 mins",
        distance: "3.0 km",
        discount: ""
    }
];
